### ISSUE TITLE
Total downloads count

### ISSUE THREAD

**Issue by ravidreams** [nithyadurai87/fte-ebooks-download-counter#1]
Hi Nithya, 

Can you add a total downloads counter of all books and all versions?

This can be displayed at the top prominently.

**Comment by nithyadurai87** [comment]
done.

**Comment by ravidreams** [comment]
Thanks, Nithya. 

Some prominent CSS styling will help to highlight the impact of this project. 

Example styling: https://wordpress.org/download/counter/
